### ISSUE TITLE
Продумывание кейсов по модулю объяснения результатов работы ML моделей с помощью каузальных моделей

### ISSUE THREAD

**Issue by Anaxagor** [Anaxagor/applyBN#2]

**Comment by Anaxagor** [comment]
Варианты возможных кейсов:
1) Расчёт важности признаков
2) Проведение A/B тестирования
3) Оценка уверенности предсказания семплов для ML модели на основе каузальных моделей (DataCentric AI + Causal Models)
4) Использование каузальных моделей для прореживания слоёв NN.

**Comment by jrzkaminski** [comment]
1. Важность признаков может быть расчитана двумя способами:

  - Простой: обучаем эго-бс с вайтлистом только на те ребра, которые входят в таргет, тут можно применять exhaustive search, потому что пространство поиска маленькое даже для больших датасетов с сотнями узлов. 
  - Посложнее: Использовать independence test как инструмент для расчета p-value, на основе этого делать вывод о "силе" связи между узлами как [тут](https://erdogant.github.io/bnlearn/pages/html/independence_test.html)

2. Для A/B тестирования есть много вариаций, включая те, что представлены в DoWhy, должно быть несложно написать удобный инструмент для подсчета ATE, CATE и т.д.

3. Опции:

- Можно оценивать предсказания black-box моделей, оценивая, насколько их предсказания помещаются в распределение, полученное из БС.
- Можно попробовать генерировать данные с помощью интервенций из каузальных сетей для обучения black-box моделей.
- DataCentric AI говорит о том, что вместо того, чтобы фокусироваться на улучшении моделей, можно улучшить качество данных: то есть в нашем случае: заполнять пропуски, генерировать синтетику, ребаланс классов (Тут можно сравниваться со SMOTE)

**Comment by jrzkaminski** [comment]
1. Подмодуль для прунинга сверточных нейронных сетей на основе каузальных сетей.
Данный модуль основан [на данном исследовании](https://arxiv.org/pdf/1811.04376). 

Алгоритм, предложенный в статье, основывается на применении принципов причинно-следственного анализа для интерпретации глубоких нейронных сетей, в частности, сверточных нейронных сетей (CNN). Основная идея заключается в том, чтобы построить *structural causal model* (SCM) для конкретного аспекта CNN, что позволяет делать количественные оценки важности и влияния различных компонентов модели (например, фильтров) на ее производительность.

### Шаги алгоритма:

1. **Построение DAG-структуры**:
   - CNN уже имеет встроенную структуру в виде направленного ациклического графа (DAG). Структура DAG создается на основе связей между узлами в модели нейронной сети, где каждый узел представляет собой нейрон, группу нейронов или фильтр, а каждое соединение — направленное ребро.

2. **Применение преобразования**:
   - Важным аспектом построения SCM является выбор подходящего преобразования \(\phi\), которое позволит выразить реакцию фильтра в CNN как вещественное число. Примеры таких преобразований включают дискретизацию отклика фильтра в бинарную форму (низкая или высокая дисперсия) или использование нормы Фробениуса для числового представления матрицы отклика фильтра.

3. **Оценка структурных уравнений**:
   - На данном этапе необходимо построить уравнения, которые будут описывать причинно-следственные зависимости между узлами в DAG. Для этого решается задача регрессии, где каждому узлу \(r\) сопоставляется функция \(f\), которая зависит от его родителей \(PA_r\) в DAG.

4. **Интервенции и оценка влияния**:
   - Выполняются различные интервенции, такие как обнуление отклика определенного фильтра, с целью измерения влияния этих интервенций на производительность модели. Это позволяет количественно оценить важность каждого фильтра или слоя в модели CNN.

Этот подход позволяет не только объяснить важность отдельных компонентов модели, но и ответить на более сложные вопросы, например, как изменение одного фильтра повлияет на конечные результаты модели.

Подобный алгоритм был имплементирован в _applybn_ как для свертоных нейронных сетей, так и для нейронных сетей, которые работают с табличными данными.
Для оценки алгоритма на примере свертоных сетей используется датасет CIFAR-10, а для проверки алгоритма на обычной нейронной сети используется датасет Breast Cancer из библиотеки scikit-learn.

**Сверточная сеть, результаты**

В случае сверточной сети сначала обучается простая сверточная сеть с тремя свертками, затем происходит прунинг фильтров с нарастанием количества убранных фильтров и заметряется Accuracy на каждом этапе прунинга. Результат сравнивается со случайным прунингом такого же количества фильтров. Результат показан на картинке ниже.

![image](https://github.com/user-attachments/assets/ed4d26f6-ebba-4a64-8e21-9687ead51049)

**Простая сеть для табличных данных, результаты**
Обучается простая сеть с двумя слоями, происходит последовательный прунинг по всем слоям определенного количества нейронов. Результат сравнивается с прунингом такого же количества случайных нейронов.

![image](https://github.com/user-attachments/assets/a0635990-cbb2-4619-9acf-195d5ee811a3)

Таким образом можно сделать вывод о том, что такой метод прунинга действительно позволяет сократить количество нейронов в нейронной сети с минимальной потерей качества, что уменьшит время инференса.

**Comment by jrzkaminski** [comment]
1. Переписать код, чтобы интерфейс наследовался от `torch.nn.utils.prune.BasePruningMethod` 
2. Проверить, может ли метод убрать рандомные нейроны
3. Посмотреть статьи с датасетами для прунинга нейронок
4. Протестировать на больших нейронках (VGG19)

**Comment by jrzkaminski** [comment]
# Pruning с помощью интервенций

## Кастомная CNN с 300K параметров

WIP

## GoogleLeNet прунинг 

Прунинг LeNet, дообученной на CIFAR-10.

| Этап, GoogleLeNet (6.6M)       | Время, с |
|--------------------------------|----------|
| Дообучение на CIFAR-10, 5 эпох | 562.53   |
| Сбор откликов слоев            | 94.15    |
| Обучение структурных уравнений | 444.88   |

![lenet_pruning](https://github.com/user-attachments/assets/c7aaa277-b943-4d2f-9524-5c31676ecd23)

## ResNet18

WIP

**Comment by jrzkaminski** [comment]
# Повышение интепретируемости моделей с итеративным обучением.
## Данные
Все эксперименты выполнены на данных `breast_cancer` из репозитория `scikit-learn`.

## Алгоритм

Для измерения confidence и uncertainty используется модифицированная версия алгоритма [dataiq](https://github.com/seedatnabeel/Data-IQ).
Для измерения `causal effect` используется CausalForestDML, позволяющий рассчитывать `causal effect` при неприрывном или многокритериальном treatment.

## Описание эксперимента

Датасет разделен на `train` и `test`. Модель обучается на `train` части датасета, затем на этой же части оценивается `causal effect` каждой переменной на `confidence` модели. После этого в `n` переменных, которые больше всего влияют на `confidence` модели вносятся интервенции, меняющие форму распределения этих переменных, замеряется `confidence` модели до и после интервенций на `test` части датасета.

## Результаты

Пример того, как менятся распределение после интервенций представлен на картинке ниже
![image](https://github.com/user-attachments/assets/e7dee3ba-d470-4325-b540-64610bbaa05b)

### CatBoostClassifier
![image](https://github.com/user-attachments/assets/8834a725-03f0-4547-bfb2-5c15151292de)
![image](https://github.com/user-attachments/assets/557dde34-05e0-47c5-80ec-0da71952d522)
![image](https://github.com/user-attachments/assets/676b7663-09f5-427d-b295-194da1a38fb1)

### AdaBoostClassifier

![image](https://github.com/user-attachments/assets/7a435069-3bc0-436b-bd2e-97a1cc96d6d8)
![image](https://github.com/user-attachments/assets/89113428-5723-4239-be1e-80984cff9bce)
![image](https://github.com/user-attachments/assets/35f8bf73-d948-4620-808e-f4808ea1aca1)

### RandomForestClassifier

![image](https://github.com/user-attachments/assets/27ca8564-1485-4476-b597-ee0c514ea7a2)
![image](https://github.com/user-attachments/assets/5ecd8acc-7c6d-4de8-9a41-452a1fdd0d8a)
![image](https://github.com/user-attachments/assets/15ea924b-2fcc-4d38-91f6-44631f8192b8)

**Comment by jrzkaminski** [comment]
На основе [статьи](https://ieeexplore.ieee.org/abstract/document/9904301) был написан алгоритм, позволяющий выделять концепты и рассчитывать Causal Effect концептов на предсказанный таргет.

## Пример на датасете adult:

**Выделенные концепты**
```
Concept_0 selected features and values:
INFO:__main__:  age: range (32, 90)
INFO:__main__:  fnlwgt: range (20101, 562336)
INFO:__main__:  education-num: range (1, 16)
INFO:__main__:  capital-gain: range (0, 27828)
INFO:__main__:  capital-loss: range (0, 810)
INFO:__main__:  hours-per-week: range (2, 70)
INFO:__main__:  education: categories [' Bachelors']
INFO:__main__:  marital-status: categories [' Married-civ-spouse', ' Never-married', ' Widowed']
INFO:__main__:  occupation: categories [' Prof-specialty']
INFO:__main__:  relationship: categories [' Husband', ' Own-child']
INFO:__main__:
Concept_1 selected features and values:
INFO:__main__:  age: range (17, 72)
INFO:__main__:  fnlwgt: range (238680, 1484705)
INFO:__main__:  education-num: range (1, 16)
INFO:__main__:  capital-gain: range (0, 15024)
INFO:__main__:  capital-loss: range (0, 1594)
INFO:__main__:  education: categories [' Bachelors']
INFO:__main__:  race: categories [' Black']
INFO:__main__:
Concept_2 selected features and values:
INFO:__main__:  age: range (21, 78)
INFO:__main__:  education-num: range (6, 16)
INFO:__main__:  capital-gain: range (99999, 99999)
INFO:__main__:  capital-loss: range (0, 0)
INFO:__main__:  hours-per-week: range (20, 80)
INFO:__main__:  workclass: categories [' Private', ' Self-emp-inc']
INFO:__main__:  education: categories [' HS-grad', ' Prof-school', ' Some-college']
INFO:__main__:  marital-status: categories [' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Other-service', ' Prof-specialty']
INFO:__main__:  relationship: categories [' Husband', ' Not-in-family', ' Own-child']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_3 selected features and values:
INFO:__main__:  fnlwgt: range (20507, 353808)
INFO:__main__:  education-num: range (1, 12)
INFO:__main__:  capital-gain: range (0, 27828)
INFO:__main__:  capital-loss: range (0, 0)
INFO:__main__:  hours-per-week: range (20, 99)
INFO:__main__:  education: categories [' Bachelors', ' HS-grad', ' Some-college']
INFO:__main__:  marital-status: categories [' Divorced', ' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Craft-repair', ' Prof-specialty']
INFO:__main__:  relationship: categories [' Husband', ' Not-in-family', ' Own-child', ' Unmarried']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_4 selected features and values:
INFO:__main__:  age: range (22, 90)
INFO:__main__:  fnlwgt: range (19302, 463072)
INFO:__main__:  education-num: range (11, 16)
INFO:__main__:  capital-gain: range (0, 41310)
INFO:__main__:  capital-loss: range (0, 0)
INFO:__main__:  hours-per-week: range (1, 99)
INFO:__main__:  workclass: categories [' Private']
INFO:__main__:  education: categories [' Bachelors', ' HS-grad', ' Masters', ' Some-college']
INFO:__main__:  marital-status: categories [' Divorced', ' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Exec-managerial', ' Other-service', ' Prof-specialty']
INFO:__main__:  relationship: categories [' Husband', ' Not-in-family', ' Own-child', ' Unmarried']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_5 selected features and values:
INFO:__main__:  age: range (17, 90)
INFO:__main__:  education-num: range (1, 16)
INFO:__main__:  capital-gain: range (0, 0)
INFO:__main__:  capital-loss: range (1092, 4356)
INFO:__main__:  hours-per-week: range (1, 99)
INFO:__main__:  marital-status: categories [' Married-civ-spouse', ' Never-married']
INFO:__main__:  relationship: categories [' Husband']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_6 selected features and values:
INFO:__main__:  age: range (20, 71)
INFO:__main__:  fnlwgt: range (19302, 354923)
INFO:__main__:  education-num: range (1, 13)
INFO:__main__:  capital-gain: range (0, 34095)
INFO:__main__:  capital-loss: range (0, 974)
INFO:__main__:  education: categories [' Bachelors', ' HS-grad', ' Some-college']
INFO:__main__:  marital-status: categories [' Divorced', ' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Adm-clerical']
INFO:__main__:  relationship: categories [' Husband', ' Not-in-family', ' Own-child', ' Unmarried']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_7 selected features and values:
INFO:__main__:  age: range (18, 72)
INFO:__main__:  fnlwgt: range (19302, 446358)
INFO:__main__:  education-num: range (10, 16)
INFO:__main__:  capital-gain: range (0, 27828)
INFO:__main__:  capital-loss: range (0, 1092)
INFO:__main__:  education: categories [' Bachelors', ' HS-grad', ' Masters', ' Some-college']
INFO:__main__:  marital-status: categories [' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Craft-repair', ' Prof-specialty']
INFO:__main__:  relationship: categories [' Husband', ' Not-in-family']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_8 selected features and values:
INFO:__main__:  age: range (17, 47)
INFO:__main__:  fnlwgt: range (19214, 444822)
INFO:__main__:  education-num: range (1, 13)
INFO:__main__:  capital-gain: range (0, 41310)
INFO:__main__:  capital-loss: range (0, 155)
INFO:__main__:  hours-per-week: range (1, 70)
INFO:__main__:  workclass: categories [' Private']
INFO:__main__:  education: categories [' Bachelors', ' Some-college']
INFO:__main__:  marital-status: categories [' Divorced', ' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Exec-managerial', ' Other-service', ' Prof-specialty']
INFO:__main__:  relationship: categories [' Husband', ' Own-child']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_9 selected features and values:
INFO:__main__:  age: range (27, 90)
INFO:__main__:  fnlwgt: range (20101, 562336)
INFO:__main__:  education-num: range (1, 15)
INFO:__main__:  capital-gain: range (0, 41310)
INFO:__main__:  capital-loss: range (0, 810)
INFO:__main__:  hours-per-week: range (2, 70)
INFO:__main__:  education: categories [' 7th-8th', ' Bachelors']
INFO:__main__:  marital-status: categories [' Married-civ-spouse', ' Never-married', ' Widowed']
INFO:__main__:  occupation: categories [' Prof-specialty']
INFO:__main__:  relationship: categories [' Husband', ' Own-child']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_10 selected features and values:
INFO:__main__:  age: range (17, 49)
INFO:__main__:  fnlwgt: range (19214, 352640)
INFO:__main__:  education-num: range (1, 12)
INFO:__main__:  capital-gain: range (0, 27828)
INFO:__main__:  capital-loss: range (0, 974)
INFO:__main__:  hours-per-week: range (25, 99)
INFO:__main__:  workclass: categories [' Private']
INFO:__main__:  education: categories [' Bachelors', ' HS-grad']
INFO:__main__:  marital-status: categories [' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Prof-specialty']
INFO:__main__:  relationship: categories [' Husband', ' Not-in-family', ' Own-child']
INFO:__main__:
Concept_11 selected features and values:
INFO:__main__:  age: range (23, 90)
INFO:__main__:  fnlwgt: range (19302, 454063)
INFO:__main__:  education-num: range (11, 16)
INFO:__main__:  capital-gain: range (0, 41310)
INFO:__main__:  capital-loss: range (0, 0)
INFO:__main__:  hours-per-week: range (1, 99)
INFO:__main__:  workclass: categories [' Private']
INFO:__main__:  education: categories [' Bachelors', ' HS-grad', ' Masters', ' Some-college']
INFO:__main__:  marital-status: categories [' Divorced', ' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Exec-managerial', ' Other-service', ' Prof-specialty']
INFO:__main__:  relationship: categories [' Husband', ' Not-in-family', ' Own-child', ' Unmarried']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_12 selected features and values:
INFO:__main__:  age: range (17, 72)
INFO:__main__:  fnlwgt: range (266084, 1484705)
INFO:__main__:  education-num: range (1, 16)
INFO:__main__:  capital-gain: range (0, 15024)
INFO:__main__:  capital-loss: range (0, 1594)
INFO:__main__:  hours-per-week: range (5, 99)
INFO:__main__:  race: categories [' Black']
INFO:__main__:
Concept_13 selected features and values:
INFO:__main__:  age: range (19, 90)
INFO:__main__:  fnlwgt: range (20507, 353808)
INFO:__main__:  education-num: range (2, 12)
INFO:__main__:  capital-gain: range (0, 27828)
INFO:__main__:  capital-loss: range (0, 0)
INFO:__main__:  hours-per-week: range (20, 99)
INFO:__main__:  education: categories [' Bachelors', ' HS-grad', ' Some-college']
INFO:__main__:  marital-status: categories [' Divorced', ' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Craft-repair', ' Prof-specialty']
INFO:__main__:  relationship: categories [' Husband', ' Not-in-family', ' Own-child', ' Unmarried']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_14 selected features and values:
INFO:__main__:  age: range (17, 90)
INFO:__main__:  education-num: range (1, 16)
INFO:__main__:  capital-gain: range (0, 0)
INFO:__main__:  capital-loss: range (1092, 4356)
INFO:__main__:  hours-per-week: range (1, 99)
INFO:__main__:  marital-status: categories [' Married-civ-spouse', ' Never-married']
INFO:__main__:  relationship: categories [' Husband']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_15 selected features and values:
INFO:__main__:  age: range (22, 74)
INFO:__main__:  fnlwgt: range (19395, 372181)
INFO:__main__:  education-num: range (1, 15)
INFO:__main__:  capital-gain: range (0, 34095)
INFO:__main__:  capital-loss: range (0, 974)
INFO:__main__:  hours-per-week: range (7, 99)
INFO:__main__:  education: categories [' Bachelors', ' HS-grad', ' Some-college']
INFO:__main__:  marital-status: categories [' Divorced', ' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Adm-clerical']
INFO:__main__:  relationship: categories [' Husband', ' Not-in-family', ' Own-child', ' Unmarried', ' Wife']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_16 selected features and values:
INFO:__main__:  age: range (18, 72)
INFO:__main__:  fnlwgt: range (19302, 447739)
INFO:__main__:  education-num: range (11, 16)
INFO:__main__:  capital-gain: range (0, 27828)
INFO:__main__:  capital-loss: range (0, 1092)
INFO:__main__:  hours-per-week: range (8, 99)
INFO:__main__:  education: categories [' Bachelors', ' HS-grad', ' Masters', ' Some-college']
INFO:__main__:  marital-status: categories [' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Craft-repair', ' Prof-specialty']
INFO:__main__:  relationship: categories [' Husband', ' Not-in-family']
INFO:__main__:  sex: categories [' Female', ' Male']
INFO:__main__:
Concept_17 selected features and values:
INFO:__main__:  age: range (17, 52)
INFO:__main__:  education-num: range (1, 16)
INFO:__main__:  capital-gain: range (0, 34095)
INFO:__main__:  capital-loss: range (0, 0)
INFO:__main__:  hours-per-week: range (1, 36)
INFO:__main__:  workclass: categories [' Private']
INFO:__main__:  education: categories [' Bachelors', ' HS-grad', ' Some-college']
INFO:__main__:  marital-status: categories [' Divorced', ' Married-civ-spouse', ' Never-married']
INFO:__main__:  occupation: categories [' Craft-repair', ' Exec-managerial', ' Other-service']
INFO:__main__:  relationship: categories [' Husband', ' Not-in-family', ' Own-child']
INFO:__main__:  sex: categories [' Female', ' Male']

**Causal Effect концептов на предсказываемый таргет**
```python
Ranking of Concepts by Estimated Coefficient (Causal Effect) on L_f:
INFO:__main__:Concept_2: Causal Effect = 17.1088
INFO:__main__:Concept_8: Causal Effect = -2.3031
INFO:__main__:Concept_4: Causal Effect = 2.1576
INFO:__main__:Concept_16: Causal Effect = 1.8638
INFO:__main__:Concept_13: Causal Effect = 1.6669
INFO:__main__:Concept_17: Causal Effect = -1.6155
INFO:__main__:Concept_7: Causal Effect = -1.0631
INFO:__main__:Concept_14: Causal Effect = 1.0002
INFO:__main__:Concept_5: Causal Effect = 1.0002
INFO:__main__:Concept_11: Causal Effect = 0.5063
INFO:__main__:Concept_10: Causal Effect = -0.4951
INFO:__main__:Concept_3: Causal Effect = -0.4441
INFO:__main__:Concept_9: Causal Effect = -0.3698
INFO:__main__:Concept_6: Causal Effect = -0.2171
INFO:__main__:Concept_12: Causal Effect = 0.1012
INFO:__main__:Concept_0: Causal Effect = -0.0965
INFO:__main__:Concept_15: Causal Effect = 0.0256
INFO:__main__:Concept_1: Causal Effect = 0.0204

```

**Comment by jrzkaminski** [comment]
Постановка эксперимента:

1. Отделяем валидационную подвыборку
2. В валидационной подвыборке размечаем концепты
3. Предсказываем внутри концептов Confidence и Uncertainty (брал среднее)
4. Смотрим полученные распределения предсказанные, сравниваем с реальными.

```python
INFO:__main__:Correlation between predicted and actual confidence: 0.4781
INFO:__main__:Correlation between predicted and actual uncertainty: 0.5970
```


![image](https://github.com/user-attachments/assets/1f838c8b-ee13-42d0-bf34-d509dd8e777d)
![image](https://github.com/user-attachments/assets/b48b1f39-7fa9-4e3e-968e-6270cc8974b0)
![image](https://github.com/user-attachments/assets/9003ae76-0231-4e9e-b859-f56a8584ec9f)
![image](https://github.com/user-attachments/assets/59977c21-98e7-4f41-857e-d2e268efb5fa)
