### ISSUE TITLE
Продумывание кейсов для модуля генерации синтетических данных

### ISSUE THREAD

**Issue by Anaxagor** [Anaxagor/applyBN#4]

**Comment by Anaxagor** [comment]
Варианты для тестирования:
1) Тестирование на подгруппах, где БС генерирует эти подгруппы (можно посмотреть в статье https://proceedings.neurips.cc/paper_files/paper/2023/file/05fb0f4e645cad23e0ab59d6b9901428-Paper-Conference.pdf)
2) Тестирования на разных режимах уверенности модели (Data Centric AI + генерация)
Варианты для тренировочных данных:
1) Расширение малой выборки
Варианты для исследовательских задач:
1) Сравнение выборок между собой
2) Расчёт каких-то характеристик для выборок

**Comment by ilia269** [comment]
Описание планируемых экспериментов и результаты проведённых -- [тут ](https://www.notion.so/982f584a54224db3bf1b97532c7a8f27?pvs=4)

Презентация по проведённых экспериментам [тут ](https://docs.google.com/presentation/d/1HthtcfLQIrGBh6Eyjk0jywDk3qdFeioNnseXxEJDk3k/edit?usp=sharing)
