### ISSUE TITLE
Продумывание кейсов для модуля отбора и генерации признаков

### ISSUE THREAD

**Issue by Anaxagor** [Anaxagor/applyBN#5]

**Comment by Anaxagor** [comment]
Продумать конкретные практические кейсы и варианты использования модуля отбора и генерации признаков на основе БС.

**Comment by Rubin-Ivan** [comment]
# Отбор признаков с помощью БС

### Причины:

- упрощение модели для повышения интерпретируемости
- для сокращения времени обучения
- во избежание проклятия размерности
- улучшение обобщающей способности модели и борьба с переобучением

### Возможности:

- отбор по марковского окружению
- отбор по MI 
- изучение стабильности CV

## Пример отбора признаков с помощью марковского окружения
![photo1718641451](https://github.com/Anaxagor/applyBN/assets/114616184/409f3dff-330b-46b1-a411-d7c1f544a1ab)

### Ограничения
Размерность датасета

### Эксперименты

**Comment by Rubin-Ivan** [comment]
# Генерация признаков с помощью БС

feature engineering / feature construction / feature extraction / feature generation

создание нового признака из 1 или неск. объектов

### Причины

- улучшает производительность модели
- позволяет использовать менее сложные модели

### Возможности 

- создание дополнительных признаков на основе вероятностных зависимостей между признаками

![image](https://github.com/Anaxagor/applyBN/assets/114616184/72f92f2d-aca6-4c92-a6d4-025754c75754)
